config/routes.rb
Rails.application.routes.draw do

  # 顧客
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 顧客
  scope module: :public do
    root to: "homes#top"
    resources :post_movies do
      resources :post_comments, only: [:create, :destroy]
    end

    get "customers/my_page" => "customers#mypage", as: "mypage"
    get "customers/:id/show" => "customers#show", as: "customerpage"
    get "costomers/infomation/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    # 検索機能
    get "search" => "searches#search"
  end

    # 管理者
    namespace :admin do
      root to: "homes#top"
      resources :post_movies, only: [:index, :show, :destroy]
      resources :customers, only: [:index, :show, :edit, :update]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>映画と出会う</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/5190e400d3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class "shadow-sm">
      <nav class="navbar navbar-expand-sm navbar-dark bg-danger">
        <div class="container">
          <a class="navbar-brand" href="/">
            <strong><span>Movies</span></strong>
          </a>

          <!-- レスポンシブ対応のハンバーガーメニューのトグルボタン -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to '映画投稿フォーム', new_post_movie_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "映画一覧", post_movies_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to 'マイページ', mypage_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "映画一覧", admin_post_movies_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "映画一覧", post_movies_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ゲストログイン(閲覧用)", customers_guest_sign_in_path, method: :post, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>" style="font-size: smaller;"><%= message %></div>
      <% end %>
    <%= yield %>
    </main>

    <footer class="bg-danger text-dark pt-2 pb-3">
      <p class="text-center d-flex align-items-center justify-content-center">©MOVIE／あなたに良い出会いがありますように</p>
      <p class="bg-dark text-white d-flex align-items-center justify-content-center"><a>Privacy Policy / プライバシーポリシー</a></p>
    </footer>

    <!-- Bootstrap JavaScript、Popper.js、jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgydCEK98tOZ5CB7f9IXd9QFqOkytc9GYQQxH3eZLXAlEXlM+9tbjPLtb8F" crossorigin="anonymous"></script>

  </body>
</html>